eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: index-data-service
  redis:
    database: 1
zipin:
  base-url: http://localhost:9411