spring:
  application:
    name: trend-trading-backtest-view
  thymeleaf:
    mode: LEGACYHTML5
    servlet:
      content-type: text/html
    cache: false

eureka:
  client:
    eureka-server-u-r-l-context: http://localhost:8761/eureka/
zipin:
  base-url: http://localhost:9411